[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["pip install -r backend_django/requirements.txt"]

[phases.build]
cmds = ["cd backend_django && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend_django && gunicorn smart_road_system.wsgi:application --bind 0.0.0.0:$PORT"
