[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend_django && gunicorn smart_road_system.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
